name: Download and Extract Zip from Google Drive

on:
  push:
    branches:
      - main  # Action akan berjalan ketika ada push ke branch 'main'

jobs:
  download_and_extract:
    runs-on: ubuntu-latest

    steps:
      # Langkah untuk checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install gdown untuk mendownload dari Google Drive
      - name: Install gdown
        run: |
          sudo apt update
          sudo apt install python3-pip -y
          pip3 install gdown

      # Mendownload file zip dari Google Drive
      - name: Download file from Google Drive
        run: |
          gdown https://drive.google.com/uc?id=1kfpysFE9NkyiIBcNn-mck5f7xLEJHfvk -O downloaded_file.zip

      # Mengekstrak file zip
      - name: Extract zip file
        run: |
          unzip downloaded_file.zip -d ./extracted_files

      # Menampilkan isi direktori untuk verifikasi
      - name: List extracted files
        run: |
          ls -la ./extracted_files

      # Memindahkan hasil ekstraksi ke direktori kerja repository
      - name: Move extracted files to repo
        run: |
          mv ./extracted_files/* ./

      # Commit perubahan ke repository
      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Add extracted files from zip"
          git push
