name: Download and Extract Zip from Google Drive

on:
  push:
    branches:
      - main  # Action akan berjalan ketika ada push ke branch 'main'

jobs:
  download_and_extract:
    runs-on: ubuntu-latest

    steps:
      # Langkah untuk checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install gdown untuk mendownload dari Google Drive
      - name: Install gdown
        run: |
          sudo apt update
          sudo apt install python3-pip -y
          pip3 install lz4
          pip3 install gdown

      # Mendownload file zip dari Google Drive
      - name: Download file from Google Drive
        run: |
          gdown https://drive.google.com/uc?id=1kfpysFE9NkyiIBcNn-mck5f7xLEJHfvk -O downloaded_file.zip

      # Mengekstrak file zip
      - name: Extract zip file
        run: |
          unzip downloaded_file.zip -d ./extracted_files

      
      # Mengekstrak file .tar.md5 (abaikan checksum md5)
      - name: Extract .tar.md5 file
        run: |
          for file in ./extracted_files/*.tar.md5; do
            if [ -f "$file" ]; then
              echo "Extracting $file..."
              tar -xf "$file" -C ./extracted_files
            fi
          done
      # Menampilkan isi direktori untuk verifikasi
      - name: List extracted files
        run: |
          ls -la ./extracted_files
      - name: Decompress .img.lz4 file
        run: |
          for file in ./extracted_files/*.img.lz4; do
            if [ -f "$file" ]; then
              lz4 -d "$file" "${file%.lz4}"  # Menghapus ekstensi .lz4 untuk hasil
            fi
          done

      - name: List final extracted .img files
        run: |
          ls -la ./extracted_files


      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: | 
            ./extracted_files/super.img.lz4
          name: extract1
          tag_name: file1
          body: |
            isi:fw
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
