name: Build and Release Nusantara ROM

on:
  push:
    branches:
      - main  # Sesuaikan dengan nama cabang Anda

jobs:
  build:
    runs-on: ubuntu-latest  # Gunakan runner yang sesuai

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install openjdk-8-jdk -y
          sudo apt-get update && sudo apt-get install git-core gnupg flex bison gperf libsdl1.2-dev squashfs-tools build-essential zip curl libncurses5-dev zlib1g-dev openjdk-8-jre openjdk-8-jdk pngcrush schedtool libxml2 libxml2-utils xsltproc lzop libc6-dev schedtool g++-multilib lib32z1-dev lib32ncurses5-dev  gcc-multilib maven tmux screen w3m ncftp

      - name: gitclone
        run: |
            git clone https://github.com/akhilnarang/scripts; cd scripts; sudo bash setup/android_build_env.sh
            
      - name: repo
        run: |
           mkdir evo && cd evo
           repo init -u https://github.com/Evolution-X/manifest -b elle
           repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
            
      - name: Source Environment Setup
        run: |
          . build/envsetup.sh

      - name: Configure ROM Build
        run: |
          aosp_$device-userdebug
        # Gantilah "device_codename" dan "buildtype" sesuai dengan perangkat dan build type Anda.

      - name: Build ROM
        run: |
          mka bacon
        # Sesuaikan dengan perintah kompilasi yang sesuai dengan proyek Anda.

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/*.img
            ${{ steps.pwd.outputs.workspace-folder }}/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/*.zip
          name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: |
            Manifest: ${{ github.event.inputs.MANIFEST_BRANCH }}
            Device: ${{ github.event.inputs.DEVICE_NAME }}
            Target: ${{ github.event.inputs.BUILD_TARGET }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
