name: Sign APK

on:
  workflow_dispatch:  # Jalankan workflow secara manual
    # Jalankan setiap kali ada push ke branch main

jobs:
  sign-zip:
    runs-on: ubuntu-latest       # Jalankan di mesin virtual Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Tarik (checkout) repo ini
    - name: Setup Java 8
      uses: actions/setup-java@v1
      with:
        java-version: '8'   # Mengatur Java 8 untuk kompatibilitas dengan signapk.jar
    - name: Run signapk.jar to sign zip
      run: |
        java -jar signapk.jar testkey.x509.pem testkey.pk8 unsigned.zip install.zip  
    - name: List final extracted .img files
      run: |
        ls 

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
          files: | 
            install.zip
          name: s
          tag_name: fil
          body: |
            isi:su
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}         # Path ke file yang ditandatangani (hasil output)
