name: Extract su binary from boot.img

on:
  push:
    branches:
      - main  # Ganti dengan cabang yang sesuai

jobs:
  extract-su:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y abootimg wget unmkbootimg

      - name: Download boot.img from GitHub Releases
        run: |
          
          # Mengunduh boot.img
          wget --no-check-certificate https://github.com/zentrust1/Tes/releases/download/V1.1/boot.img -O boot.img

      - name: Extract su from boot.img
        run: |
          OUTPUT_DIR="extracted_su"

          mkdir -p $OUTPUT_DIR

          # Ekstrak image
          abootimg -x boot.img

          # Temukan dan salin binary su
          if [ -f "initrd.img" ]; then
            mkdir -p initrd_extracted
            cd initrd_extracted
            gzip -dc ../initrd.img | cpio -idmv

            # Ganti dengan path yang sesuai jika lokasi binary su berbeda
            cp sbin/su ../$OUTPUT_DIR/
            cd ..
          fi
      - name: Extract su from boot.img
        run: |
          OUTPUT_DIR="extracted_su"
          mkdir -p $OUTPUT_DIR

          # Ekstrak boot.img
          unmkbootimg boot.img

          # Ekstrak ramdisk jika ada
          if [ -f "ramdisk.cpio.gz" ]; then
            mkdir -p ramdisk_extracted
            gunzip -c ramdisk.cpio.gz | cpio -idmv -D ramdisk_extracted

            # Temukan dan salin binary su
            cp ramdisk_extracted/sbin/su $OUTPUT_DIR/
          fi
      - name: List final extracted .img files
        run: |
          ls -la ./extracted_su


      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: | 
            ./extracted_su/su
            
          name: su
          tag_name: file3
          body: |
            isi:su
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
