name: Extract su binary from boot.img

on:
  workflow_dispatch:  # Ganti dengan cabang yang sesuai

jobs:
  extract-su:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y abootimg wget

      - name: Download boot.img from GitHub Releases
        run: |
          # Mengunduh boot.img
          wget --no-check-certificate https://github.com/zentrust1/Tes/releases/download/V1.1/boot.img -O boot.img

      - name: Extract su from boot.img
        run: |
          OUTPUT_DIR="extracted_su"
          mkdir -p $OUTPUT_DIR

          
          abootimg -x boot.img

          # Ekstrak ramdisk
          if [ -f "initrd.img" ]; then
            mkdir -p initrd_extracted
            cd initrd_extracted
            
            sudo chmod 777 ../initrd.img
            sudo gzip -dc ../initrd.img | sudo cpio -idmv

            
            sudo cp system/bin/su ../$OUTPUT_DIR/ || echo "su binary not found"
            cd ..
          fi
     
      - name: List final extracted .img files
        run: |
          ls -la ./extracted_su

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: | 
            ./extracted_su/su
          name: su
          tag_name: file3
          body: |
            isi:su
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
